- python
    - python is a programming paradism means it supports functional programming and object oriented programming and also works with procedure oriented programming
- procedure oriented language
    - procedur oriented means write our programming language using functions and object and classes
- object oriented language
    - object:- real world entity (or) it is a physical entity
    - class:- logical entity contains logic of the application


In [ ]:
# syntax of class
class class_name:
    variables
    methods or functions

In [1]:
print("hi hello")

hi hello


In [2]:
8+9

17

In [19]:
class Hi:
    a=10
    b=30
    name="sateesh"
    def show():
        print(" iam from show() function")

In [20]:
Hi.name


'sateesh'

In [21]:
Hi.show()

 iam from show() function


In [22]:
Hi.a

10

In [23]:
Hi.b

30

In [24]:
print(Hi.a,Hi.b,Hi.name)
Hi.show()

10 30 sateesh
 iam from show() function


In [27]:
class Hi:
    name="progarm"
    program_name="python"
    def display():
        print("iam from display function()")
    def  show():
        print("iam from showfunction()")
print(Hi.name,Hi.program_name)
print(Hi.display())
print(Hi.show())

progarm python
iam from display function()
None
iam from showfunction()
None


In [33]:
class Hello:
    def display():
        print("iam from display function()")
        return ("iam from return statement")
    def show():
        print("iam from showfunction()")
print(Hello.display())
print(Hello.show())

iam from display function()
iam from return statement
iam from showfunction()
None


In [3]:
# in java obj declaration 
    # class_name obj_name = new_classname
# in python
        # obj_name=class_name
    

In [37]:
class Hi:
    name="progarm"
    program_name="python"
    def display(self):
        print("iam from display function()")
        return("iam from return statement")
    def  show():
        print("iam from showfunction()")
obj=Hi()
print(obj.name,obj.program_name)
print(obj.display())

progarm python
iam from display function()
iam from return statement


# constructor 
- Construcor::with out using object we will call methods
    - in java:: class name should be same as method name
    - in python:: we will use one special method to define construcor
    - __init(self)__

In [5]:
class Hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("hi",self.name)
    def display(self):
        print("your roll_no",self.roll_no)
obj=Hai('sateesh','21A85A0521')
obj.display()

hi sateesh
your roll_no 21A85A0521


# Inheritance
- inserts something from parent class to child class


In [ ]:
class A:
    # a,b=10,20
class B(A):
    # c,d=40,50

In [6]:
class A:
    a,b=10,20
    def msg():
        print("iam from class A")
class B(A):
    c,d=40,50
    def msg1():
        print("iam from class B")
obj=B
print(obj.c,obj.a)
obj.msg()
obj.msg1()

40 10
iam from class A
iam from class B


# python libraries for data science
- organizing,processing and analyzing the huge amount of data
- apply data visualization
- extracting the from the source
- nearly 20 python libraries are there
# top 
- Numpy
- Pandas
- Matplotlib

# Numpy
- numpy::(num+py) means numerical data+python
- it is a fundemental package for scientific computing in python
- numpy is python library
- it is used to create multidimensional arrays for fast operations
    - its dealing with mathematical,scientific,statical data
- numpy contains a powerful n-dimensional array object.which in the form of row and coloumns
- we can initilize numpy arrays from nested python lists


In [ ]:
# hoe to intall numpy
- pip install numpy

In [8]:
# how to import and use numpy package
import numpy as np

In [10]:
# how to find the numpy vaersion 
np.__version__

'1.20.3'

In [13]:
# how to crerate numpy arrays
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)
print(type(a2))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [17]:
# to know about the shape of the array 
a2.shape

(2, 5)

In [19]:
li=[2,3,4,'h','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' 'h' 'i']
<class 'numpy.ndarray'>


In [20]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
print(ar.dtype)

int32


In [24]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [25]:
b.shape

(2, 2)

In [26]:
b.itemsize

4

In [27]:
b.ndim

2

In [28]:
# range
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [31]:
# arange()- third party of numpy library
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [34]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x=np.arange(10)
print(x)
print(x.reshape(5,2))

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [43]:
# reshape of array
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("before reshape",a1)
print(a1.ndim)
a2=a1.reshape(4,2)
print("after reshape",a2)
print(a2.shape)
print(a2.ndim)

(8,)
before reshape [1 2 3 4 5 6 7 8]
1
after reshape [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [50]:
# resize of array (its modifies shape and array itself)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3) #resize the no of elements from origianl array
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [51]:
# Zero array
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [52]:
# one array
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [53]:
# full array - full (dimentions,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [54]:
np.diag(a)

array([7, 7, 7])

In [55]:
np.full(3,100)

array([100, 100, 100])

In [56]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [57]:
# eye array
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [58]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [60]:
r=np.random.randint(1,10)
r

4

In [61]:
n=np.random.randint(1,19,12).reshape(3,4)
n

array([[18, 17,  9, 11],
       [16,  3,  9, 16],
       [11,  2, 13, 16]])

In [62]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.1902458 , 0.91425878, 0.79279869],
       [0.47224853, 0.40374067, 0.39844418]])

In [63]:
f=np.random.randn(2,3)
f

array([[-0.24339013, -1.3479294 ,  0.58827637],
       [ 0.45716583,  0.60949143, -0.07731932]])

In [64]:
a=np.random.randint(1,30,(10,3))
a

array([[18, 23, 26],
       [22, 17, 10],
       [ 3, 29, 28],
       [ 5, 12, 20],
       [ 1, 16, 22],
       [18,  6,  8],
       [10, 15, 10],
       [ 4,  2, 19],
       [17, 27,  9],
       [12,  2, 28]])

In [65]:
a[1:5]

array([[22, 17, 10],
       [ 3, 29, 28],
       [ 5, 12, 20],
       [ 1, 16, 22]])

In [66]:
a[2:6]

array([[ 3, 29, 28],
       [ 5, 12, 20],
       [ 1, 16, 22],
       [18,  6,  8]])

In [67]:
a>10

array([[ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [68]:
[a>10]
a 

array([[18, 23, 26],
       [22, 17, 10],
       [ 3, 29, 28],
       [ 5, 12, 20],
       [ 1, 16, 22],
       [18,  6,  8],
       [10, 15, 10],
       [ 4,  2, 19],
       [17, 27,  9],
       [12,  2, 28]])

In [69]:
a[a>10].sum()


369

In [70]:
a.min()

1

In [71]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [77]:
print(a+b)
print("+ + + + + + + + + +")
print(a-b)
print("_________________")
print(a*b)
print("******************")
print(a/b)
print("/////////////////////")
print(np.max(a))
print(np.max(b))


[[10 12 14]
 [16 18 20]
 [22 24 26]]
+ + + + + + + + + +
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
_________________
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
******************
[[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]
/////////////////////
8
18


In [78]:
# 0 to 15-->(3,5)
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [79]:
print(np.mean(a))

7.0


In [80]:
print(np.median(a))

7.0


In [81]:
b.dot(a)

array([[175, 208, 241, 274, 307],
       [220, 262, 304, 346, 388],
       [265, 316, 367, 418, 469]])

In [82]:
a+10


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
np.log2(2)

1.0

In [90]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [91]:
np.exp(1)

2.718281828459045

In [93]:
np.sin(0)

0.0

In [87]:
np.sin(30)

-0.9880316240928618

In [94]:
np.cos(0)

1.0

In [92]:
np.cos(30)

0.15425144988758405

In [95]:
np.tan(0)

0.0

In [86]:
np.tan(30)

-6.405331196646276

In [96]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

# Pandas 
- pandas is datascience package 
- It is used for 
    - data manipulation(modifications and updations)
    - data analysis
    - Data cleaning(means rermoving unnecesssray data from datasets)
- contains mainly two data structures in pandas
     - series--Sequence of data
     - Data frames-- Data with row and coloumn